CREATE TABLE AA_Registrant (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(25)  NOT NULL,
    email        VARCHAR(255) NOT NULL,
    phone_number VARCHAR(12)  NOT NULL,
    CONSTRAINT uq_aa_registrant_email UNIQUE (email)
);
