-- Initial schema — mirrors the AA_Registrant table inferred from Member.java
-- Source: ejb/src/main/java/.../model/Member.java (@Table, @Column, @UniqueConstraint)
-- Replaces hbm2ddl.auto=create-drop from persistence.xml
CREATE TABLE AA_Registrant (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(25)  NOT NULL,
    email        VARCHAR(255) NOT NULL,
    phone_number VARCHAR(12)  NOT NULL,
    CONSTRAINT uq_aa_registrant_email UNIQUE (email)
);
